name: Wake Arena Audit
run-name: ${{ github.actor }} prepared Wake Arena PR
on:
  push:
    branches:
      - master #todo change to your main branch
jobs:
  perform-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install code dependencies
        run: {{ install deps }} #todo replace
      - name: Setup Wake arena
        uses: Ackee-Blockchain/wake-arena-setup-action@0.1.1
      - name: Perform audit
        env:
          WAKE_ARENA_API_KEY: ${{ secrets.WAKE_ARENA_API_KEY }}
        run: wake-arena check --name "${{ github.event.head_commit.message }}" --project "Bfzxvqsl"
